PUBLIC_MESSAGES = {
    "internal_error": "İşlem tamamlanamadı. Takip koduyla destek isteyebilirsiniz.",
    "authentication_required": "Geçerli bir kullanıcı kimliği gerekli.",
    "user_disabled": "Kullanıcı hesabı devre dışı.",
    "admin_required": "Bu işlem için yönetici yetkisi gerekli.",
    "not_found": "Kayıt bulunamadı.",
    "document_not_found": "Belge bulunamadı.",
    "analysis_not_found": "Analiz bulunamadı.",
    "source_not_found": "Kaynak belge bulunamadı.",
    "invalid_request": "İstek işlenemedi. Gönderdiğiniz bilgileri kontrol edin.",
    "validation_error": "İstek alanları geçersiz veya eksik.",
    "method_not_allowed": "Bu istek yöntemi desteklenmiyor.",
    "forbidden": "Bu işlem için yetkiniz yok.",
    "conflict": "İşlem mevcut durumla çakışıyor.",
    "analysis_not_completed": "Eşleşmeler yalnız tamamlanmış analizlerde okunabilir.",
    "analysis_not_available": "Belge analiz için uygun durumda değil.",
    "storage_unavailable": "Dosya depolama servisine şu anda ulaşılamıyor. Yeniden deneyin.",
    "document_conflict": "Belge kaydı oluşturulamadı; yeniden deneyin.",
    "source_conflict": "Bu kaynak dosya veya depolama konumu zaten kayıtlı.",
    "source_disabled": "Pasif bir kaynak yeniden indekslenemez.",
    "source_processing": "Kaynak zaten işleniyor.",
    "source_reindex_conflict": "Kaynak parçaları kullanımda olduğu için yeniden indekslenemedi.",
    "source_checksum_mismatch": "Kaynak dosya kayıtlı içerikle eşleşmiyor.",
    "invalid_source_metadata": "Kaynak bilgileri geçersiz. Zorunlu alanları kontrol edin.",
    "unsupported_source_type": "Kaynak dosyanın içerik türü desteklenmiyor.",
    "invalid_upload": "Dosya yüklenemedi. Dosyayı kontrol edip yeniden deneyin.",
    "file_too_large": "Dosya boyutu 20 MB sınırını aşıyor.",
    "empty_file": "Boş dosya yüklenemez.",
    "unsupported_file_type": "Yalnızca PDF, DOCX ve TXT dosyaları kabul edilir.",
    "file_signature_mismatch": "Dosya bozuk olabilir veya uzantısı içeriğiyle eşleşmiyor.",
    "encrypted_document": "Şifreli belgenin şifresini kaldırıp yeniden yükleyin.",
    "encrypted_pdf": "Şifreli PDF dosyasının şifresini kaldırıp yeniden yükleyin.",
    "invalid_pdf": "PDF açılamadı. Dosyayı yeniden kaydedip tekrar yükleyin.",
    "invalid_docx": "DOCX açılamadı. Dosyayı Word'de yeniden kaydedip tekrar yükleyin.",
    "empty_pdf": "PDF içinde sayfa bulunamadı.",
    "no_extractable_text": "Belgede analiz edilebilecek metin bulunamadı.",
    "unknown_text_encoding": "Metin kodlaması okunamadı. Dosyayı UTF-8 olarak kaydedin.",
    "unsafe_text_content": "Dosya güvenli metin olarak okunamadı.",
    "ocr_required": "PDF görüntü içeriyor. OCR uygulayıp yeniden yükleyin.",
    "page_extraction_failed": "PDF sayfasındaki metin okunamadı. Dosyayı kontrol edin.",
    "processing_failed": "Belge işlenemedi. Dosyayı kontrol edip yeniden deneyin.",
    "processing_timeout": "Belge işleme süresi doldu.",
    "retry_exhausted": "Servise tekrar denemelerden sonra da ulaşılamadı.",
    "stored_document_changed": "Saklanan dosya kayıtlı içerikle eşleşmiyor.",
    "missing_document_chunks": "Belgenin metin parçaları bulunamadı.",
    "missing_algorithm_snapshot": "Analizin algoritma ayarları bulunamadı.",
    "unsupported_algorithm_version": "Analizin algoritma sürümü desteklenmiyor.",
    "missing_analysis": "Belgenin analiz kaydı bulunamadı.",
}


def safe_failure_code(value: str | None) -> str | None:
    if value is None:
        return None
    return value if value in PUBLIC_MESSAGES else "processing_failed"
